//----------DHTML Menu Created using AllWebMenus PRO ver 5.0-#702---------------
//C:\Documents and Settings\¿‰ÏËÌËÒÚ‡ÚÓ\ÃÓË ‰ÓÍÛÏÂÌÚ˚\SLOVO\¿ÎÙ‡‚ËÚÃÂÌ˛3Œ .awm
var awmMenuName='menu';
var awmLibraryBuild=702;
var awmLibraryPath='/awmdata';
var awmImagesPath='/awmdata';
var awmSupported=(navigator.appName + navigator.appVersion.substring(0,1)=="Netscape5" || document.all || document.layers || navigator.userAgent.indexOf('Opera')>-1 || navigator.userAgent.indexOf('Konqueror')>-1)?1:0;
if (awmAltUrl!='' && !awmSupported) window.location.replace(awmAltUrl);
if (awmSupported){
var nua=navigator.userAgent,scriptNo=(nua.indexOf('Safari')>-1)?7:(nua.indexOf('Gecko')>-1)?2:((document.layers)?3:((nua.indexOf('Opera')>-1)?4:((nua.indexOf('Mac')>-1)?5:1)));
var mpi=document.location,xt="";
var mpa=mpi.protocol+"//"+mpi.host;
var mpi=mpi.protocol+"//"+mpi.host+mpi.pathname;
if(scriptNo==1){oBC=document.all.tags("BASE");if(oBC && oBC.length) if(oBC[0].href) mpi=oBC[0].href;}
while (mpi.search(/\\/)>-1) mpi=mpi.replace("\\","/");
mpi=mpi.substring(0,mpi.lastIndexOf("/")+1);
var e=document.getElementsByTagName("SCRIPT");
for (var i=0;i<e.length;i++){if (e[i].src){if (e[i].src.indexOf(awmMenuName+".js")!=-1){xt=e[i].src.split("/");if (xt[xt.length-1]==awmMenuName+".js"){xt=e[i].src.substring(0,e[i].src.length-awmMenuName.length-3);if (e[i].src.indexOf("://")!=-1){mpi=xt;}else{if(xt.substring(0,1)=="/")mpi=mpa+xt; else mpi+=xt;}}}}}
while (mpi.search(/\/\.\//)>-1) {mpi=mpi.replace("/./","/");}
var awmMenuPath=mpi.substring(0,mpi.length-1);
while (awmMenuPath.search("'")>-1) {awmMenuPath=awmMenuPath.replace("'","&#39;");}
document.write("<SCRIPT SRC='"+awmMenuPath+awmLibraryPath+"/awmlib"+scriptNo+".js'><\/SCRIPT>");
var n=null;
awmzindex=1000;
}

var awmImageName='';
var awmPosID='';
var awmSubmenusFrame='';
var awmSubmenusFrameOffset;
var awmOptimize=0;
var awmUseTrs=0;
var awmSepr=["0","","",""];
function awmBuildMenu(){
if (awmSupported){
awmCreateCSS(1,2,1,'#FFFFFF','#B1BACB',n,'bold x-small serif',n,'outset',1,'#DFF1FF','0px 0px 0px 0',0);
awmCreateCSS(0,2,1,'#FFFFFF','#B1BACB',n,'bold x-small serif',n,'outset',1,'#DFF1FF','0px 0px 0px 0',0);
awmCreateCSS(0,1,0,n,n,n,n,n,'none',0,'#000000',0,0);
awmCreateCSS(1,2,1,'#032785',n,n,'14px Tahoma',n,'outset',1,'#DFF1FF','0px 0px 0px 0',1);
awmCreateCSS(0,2,1,'#008EFF',n,n,'12px Tahoma',n,'inset',1,'#DFF1FF','0px 0px 0px 0',1);
awmCreateCSS(0,2,1,'#032785',n,n,'12px Tahoma',n,'outset',1,'#DFF1FF','0px 0px 0px 0',1);
var s0=awmCreateMenu(0,0,0,0,1,0,0,5,0,10,20,0,0,2,5,1,0,n,n,100,0,0,10,20,0,-1,2,200,200,0,0,0,"0,0");
it=s0.addItem(3,4,5,"  –ê  ",n,n,"","Bukva1.htm",n,n,n,"Bukva1.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –í  ",n,n,"","Bukva2.htm",n,n,n,"Bukva2.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –î  ",n,n,"","Bukva3.htm",n,n,n,"Bukva3.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ñ  ",n,n,"","Bukva4.htm",n,n,n,"Bukva4.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ò  ",n,n,"","Bukva5.htm",n,n,n,"Bukva5.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –õ  ",n,n,"","Bukva6.htm",n,n,n,"Bukva6.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ù  ",n,n,"","Bukva7.htm",n,n,n,"Bukva7.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ü  ",n,n,"","Bukva8.htm",n,n,n,"Bukva8.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –°  ",n,n,"","Bukva9.htm",n,n,n,"Bukva9.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –£  ",n,n,"","Bukva10.htm",n,n,n,"Bukva10.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –•  ",n,n,"","Bukva11.htm",n,n,n,"Bukva11.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ß  ",n,n,"","Bukva12.htm",n,n,n,"Bukva12.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –©  ",n,n,"","Bukva13.htm",n,n,n,"Bukva13.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –Æ  ",n,n,"","Bukva14.htm",n,n,n,"Bukva14.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ë  ",n,n,"","Bukva15.htm",n,n,n,"Bukva15.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ì  ",n,n,"","Bukva16.htm",n,n,n,"Bukva16.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ï  ",n,n,"","Bukva17.htm",n,n,n,"Bukva17.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ó  ",n,n,"","Bukva18.htm",n,n,n,"Bukva18.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ö  ",n,n,"","Bukva19.htm",n,n,n,"Bukva19.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –ú  ",n,n,"","Bukva20.htm",n,n,n,"Bukva20.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –û  ",n,n,"","Bukva21.htm",n,n,n,"Bukva21.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –†  ",n,n,"","Bukva22.htm",n,n,n,"Bukva22.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –¢  ",n,n,"","Bukva23.htm",n,n,n,"Bukva23.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –§  ",n,n,"","Bukva24.htm",n,n,n,"Bukva24.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –¶  ",n,n,"","Bukva25.htm",n,n,n,"Bukva25.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –®  ",n,n,"","Bukva26.htm",n,n,n,"Bukva26.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –≠  ",n,n,"","Bukva27.htm",n,n,n,"Bukva27.htm",n,0,35,2,0);
it=s0.addItem(3,4,5,"  –Ø  ",n,n,"","Bukva28.htm",n,n,n,"Bukva28.htm",n,0,35,2,0);
s0.pm.buildMenu();
}}
